"""Recommendation API schemas."""

from pydantic import BaseModel, Field

from app.schemas.supplier import SupplierScoreSchema


class CitationSchema(BaseModel):
    document_id: str | None = None
    source_document: str = "AI Engine"
    page_number: int = 1
    chunk_text: str = ""


class RankedSupplierSchema(BaseModel):
    supplier_id: str
    supplier_name: str
    country: str
    rank: int
    final_score: float
    lead_time_days: int
    scores: SupplierScoreSchema
    citations: dict[str, CitationSchema] = Field(default_factory=dict)


class RecommendationSchema(BaseModel):
    id: str | None = None
    project_id: str
    recommended_supplier_id: str
    recommended_supplier_name: str
    summary: str
    confidence_score: float
    confidence_label: str
    confidence_explanation: str
    ranking: list[RankedSupplierSchema] = Field(default_factory=list)
    pros: list[str] = Field(default_factory=list)
    pros_citations: list[CitationSchema] = Field(default_factory=list)
    cons: list[str] = Field(default_factory=list)
    tradeoffs: list[str] = Field(default_factory=list)
    # Phase 6 additions — populated by RecommendationAgent
    risks: list[str] = Field(default_factory=list)
    assumptions: list[str] = Field(default_factory=list)
    limitations: list[str] = Field(default_factory=list)
    next_actions: list[str] = Field(default_factory=list)
    evidence_ids: list[str] = Field(
        default_factory=list,
        description="Chunk IDs from ChromaDB that support this recommendation.",
    )
    ai_narrative: bool = Field(
        default=False,
        description="True when the summary/pros/cons were generated by the AI agent.",
    )
